mit Errors
Chenentano/Gruppe-3-Warehouse-Management pull request #19
Opened 2024-04-30 14:43 UTC by SilviaGuillen

2024-04-30 15:07 UTC, Chenentano requested changes
Bitte Errors beheben.

2024-04-30 15:09 UTC, CarstenKremser requested changes
Entferne bitte die Dateien unter backend/src/main/resources/static aus dem git repo, die werden sowieso immer neu gebaut.

2024-05-02 14:32 UTC, SilviaGuillen commented
errors resolved

2024-05-02 14:45 UTC, CarstenKremser requested changes
Inhalt von static nicht Committee

2024-05-02 14:51 UTC, SilviaGuillen commented
korrigiert

2024-05-02 14:59 UTC, closed without merging